### ISSUE TITLE
Needs better 'fadeOut' animation

### ISSUE THREAD

**Issue by GastroGeek** [zulu-entertainment/OSDisplay#2]
Hi.

Firstly... awesome work! This goes great with [this](https://github.com/kfix/ddcctl).

More of an aesthetic thing... but It looks as though the image fades and THEN the backdrop just vanishes sharply... is there any way you can make it more 'authentic' and fade together as with the stock look? please ;)

Keep up the great work!

GG

**Comment by AnthoPakPak** [comment]
To make a better animation, just replace following line : 
`self.view.animator.alphaValue = 0.0f;`
with 
`self.view.window.animator.alphaValue = 0.0f;`

in `ViewController.m`

**Comment by zulu-entertainment** [comment]
I got best results with combining both values :)
Thanks for the suggestion!
